# version: "3.9"
services:
  #Creates a genesis state for the beacon chain using a YAML configuration file and
  # a deterministic set of 64 validators.
  create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:v5.1.2"
    command:
      - testnet
      - generate-genesis
      # - --fork=electra
      - --fork=deneb
      - --num-validators=64
      - --output-ssz=/consensus/genesis.ssz
      - --chain-config-file=/consensus/config.yml
      - --geth-genesis-json-in=/execution/genesis.json
      - --geth-genesis-json-out=/execution/genesis.json
    volumes:
      - ./consensus:/consensus
      - ./execution:/execution
    networks: 
      - bcnetwork


  # Sets up the genesis configuration for the go-ethereum client from a JSON file.
  geth-genesis-pos:
    container_name: geth-genesis-pos
    image: "docker.io/ethereum/client-go:v1.14.11"
    command: --datadir=/execution init /execution/genesis.json
    volumes:
      - ./execution:/execution
      - ./execution/genesis.json:/execution/genesis.json
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    networks: 
      - bcnetwork


  # Runs a Prysm beacon chain from a specified genesis state created in the previous step
  # and connects to go-ethereum in the same network as the execution client.
  # The account used in go-ethereum is set as the suggested fee recipient for transactions
  # proposed via the validators attached to the beacon node.
  beacon-chain:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:v5.1.2"
    command:
      - --datadir=/consensus/beacondata
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=0
      - --genesis-state=/consensus/genesis.ssz
      - --bootstrap-node=
      - --interop-eth1data-votes
      # The chain configuration file used for setting up Prysm
      - --chain-config-file=/consensus/config.yml
      - --contract-deployment-block=0
      # We specify the chain id used by our execution client
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://geth:8551
      - --accept-terms-of-use
      - --jwt-secret=/execution/jwtsecret
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --minimum-peers-per-subnet=0
      # - --enable-debug-rpc-endpoints
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    ports:
      - 4000:4000
      - 3500:3500
      # - 8080:8080
      # - 6060:6060
      # - 32382:32382
    volumes:
      - ./consensus:/consensus
      - ./execution:/execution
      - ./execution/jwtsecret:/execution/jwtsecret
    networks: 
      - bcnetwork


  # Runs the go-ethereum execution client with the specified, unlocked account and necessary
  # APIs to allow for proof-of-stake consensus via Prysm.
  geth-pos:
    container_name: geth
    image: "docker.io/ethereum/client-go:v1.14.11"
    command:
      - --http
      - --http.addr=0.0.0.0
      - --http.api=admin,debug,engine,eth,miner,net,rpc,txpool,web3
      - --http.corsdomain=*
      - --http.port=8545
      - --http.vhosts=*
      - --ws
      - --ws.api=admin,debug,engine,eth,miner,net,rpc,txpool,web3
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/execution/jwtsecret
      - --datadir=/execution
      - --allow-insecure-unlock
      - --unlock=0x123463a4b065722e99115d6c222f267d9cabb524
      - --password=/execution/geth_password.txt
      - --nodiscover
      - --syncmode=full
      - --metrics
      - --metrics.addr=geth
      - --metrics.port=6060
      - --metrics.expensive
    ports:
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 6060:6060
    depends_on:
      geth-genesis-pos:
        condition: service_completed_successfully
      beacon-chain:
        condition: service_started
    volumes:
      - ./execution:/execution
      - ./execution/jwtsecret:/execution/jwtsecret
      - ./execution/geth_password.txt:/execution/geth_password.txt
    networks: 
      - bcnetwork


  # We run a validator client with 64, deterministically-generated keys that match
  # The validator keys present in the beacon chain genesis state generated a few steps above.
  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:v5.1.2"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/consensus/validatordata
      - --accept-terms-of-use
      - --interop-num-validators=64
      - --interop-start-index=0
      - --chain-config-file=/consensus/config.yml
    depends_on:
      beacon-chain:
        condition: service_started
    volumes:
      - ./consensus:/consensus
    networks: 
      - bcnetwork


  # Ethereum Lite Explorer by Alethio : https://github.com/Alethio/ethereum-lite-explorer
  lite-explorer:
    image: alethio/ethereum-lite-explorer
    ports:
      - 8081:80
    environment:
      - APP_NODE_URL=http://${IP_SERVER}:8545
    networks: 
      - bcnetwork
    profiles: [explorer]


  # ether-faucet by APlonks : https://github.com/APlonks/ether-faucet/tree/main
  ether-faucet-frontend:
    container_name: ether-faucet-frontend
    image: ghcr.io/aplonks/ether-faucet-frontend:main
    ports: 
      - 5001:80
    env_file:
      - .env
    networks: 
      - bcnetwork
    profiles: [ether-faucet]

  ether-faucet-backend:
    container_name: ether-faucet-backend
    image: ghcr.io/aplonks/ether-faucet-backend:main
    ports: 
      - 5002:5002
    env_file:
      - .env
    networks: 
      - bcnetwork
    profiles: [ether-faucet]

  redis-stack:
    container_name: redis-stack
    image: docker.io/redis/redis-stack:7.2.0-v9
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - bcnetwork
    profiles: [ether-faucet]

networks:
  bcnetwork:
    name: bcnetwork
    driver: bridge
    external: true
